export const QUIZ_API_ROUTES = {
  BASE: '/quizzes',
  QUIZZES: '/quizzes',
  QUIZ_BY_ID: (id: number) => `/quizzes/${id}`,
  QUIZ_QUESTIONS: (id: number) => `/quizzes/${id}/questions`,
  CREATE_QUESTION: (quizId: number) => `/quizzes/${quizId}/questions`,
  UPDATE_QUESTION: (quizId: number, questionId: number) => `/quizzes/${quizId}/questions/${questionId}`,
  DELETE_QUESTION: (quizId: number, questionId: number) => `/quizzes/${quizId}/questions/${questionId}`,
  COURSE_QUIZZES: (courseId: number) => `/quizzes/course/${courseId}`,
  SETTINGS: (id: number) => `/quizzes/${id}/settings`,
  ATTEMPTS: (quizId: number) => `/quizzes/${quizId}/attempts`,
  START_ATTEMPT: (quizId: number) => `/quizzes/${quizId}/attempts/start`,
  SUBMIT_ATTEMPT: (attemptId: number) => `/quiz-attempts/${attemptId}/submit`,
  ATTEMPT_RESULT: (attemptId: number) => `/quiz-attempts/${attemptId}/result`,
  MY_ATTEMPTS: (quizId: number) => `/quizzes/${quizId}/my-attempts`,
  BASE_ATTEMPTS: '/quiz-attempts',
  QUIZ_PROGRESS_BY_QUIZ: (quizId: number) => `/quiz-progress/${quizId}`,
  QUIZ_PROGRESS_BY_COURSE: (courseId: number) => `/quiz-progress/course/${courseId}`,
  QUIZ_PROGRESS_COMPARE: (quizId: number) => `/quiz-progress/${quizId}/compare`,
  QUIZ_PROGRESS_WEAK: (quizId: number) => `/quiz-progress/${quizId}/weak-topics`,
  QUIZ_PROGRESS_IMPROVEMENT: (quizId: number) => `/quiz-progress/${quizId}/improvement`,
  GENERATE_QUIZ: '/ai/generate/quiz',
  UPLOAD_FILE: '/files/upload',
} as const
