export const QUIZ_API_ROUTES = {
  BASE: '/quizzes',
  QUIZZES: '/quizzes',
  QUIZ_BY_ID: (id: number) => `/quizzes/${id}`,
  DUPLICATE_QUIZ: (id: number) => `/quizzes/${id}/duplicate`,
  QUIZ_QUESTIONS: (id: number) => `/quizzes/${id}/questions`,
  CREATE_QUESTION: (quizId: number) => `/quizzes/${quizId}/questions`,
  UPDATE_QUESTION: (quizId: number, questionId: number) => `/quizzes/${quizId}/questions/${questionId}`,
  DELETE_QUESTION: (quizId: number, questionId: number) => `/quizzes/${quizId}/questions/${questionId}`,
  REORDER_QUESTIONS: (quizId: number) => `/quizzes/${quizId}/questions/reorder`,
  CREATE_OPTION: (quizId: number, questionId: number) => `/quizzes/${quizId}/questions/${questionId}/options`,
  UPDATE_OPTION: (quizId: number, questionId: number, optionId: number) => `/quizzes/${quizId}/questions/${questionId}/options/${optionId}`,
  DELETE_OPTION: (quizId: number, questionId: number, optionId: number) => `/quizzes/${quizId}/questions/${questionId}/options/${optionId}`,
  COURSE_QUIZZES: '/quizzes',
  SETTINGS: (id: number) => `/quizzes/${id}/settings`,
  SETTINGS_RESET: (id: number) => `/quizzes/${id}/settings/reset`,
  PREVIEW: (id: number) => `/quizzes/${id}/preview`,
  SIMULATE: (id: number) => `/quizzes/${id}/simulate`,
  ATTEMPTS: (quizId: number) => `/quizzes/${quizId}/attempts`,
  START_ATTEMPT: `/quiz-attempts/start`,
  SUBMIT_ATTEMPT: (attemptId: number) => `/quiz-attempts/${attemptId}/submit`,
  ATTEMPT_RESULT: (attemptId: number) => `/quiz-attempts/${attemptId}/result`,
  MY_ATTEMPTS: '/quiz-attempts',
  ANSWER: '/quiz-attempts/answer',
  ANSWERS_BULK: '/quiz-attempts/answers/bulk',
  GRADE: (id: number) => `/quiz-attempts/${id}/grade`,
  REGRADE: (id: number) => `/quiz-attempts/${id}/regrade`,
  HISTORY: '/quiz-attempts/history',
  BEST: '/quiz-attempts/best',
  COMPARE: '/quiz-attempts/compare',
  BASE_ATTEMPTS: '/quiz-attempts',
  QUIZ_PROGRESS_BY_QUIZ: (quizId: number) => `/progress/quizzes/${quizId}`,
  QUIZ_PROGRESS_BY_COURSE: (courseId: number) => `/progress/quizzes/courses/${courseId}`,
  QUIZ_PROGRESS_COMPARE: '/progress/quizzes/compare',
  QUIZ_PROGRESS_WEAK: (courseId: number) => `/progress/quizzes/courses/${courseId}/weak-topics`,
  QUIZ_PROGRESS_IMPROVEMENT: '/progress/quizzes/improvement',
  QUIZ_AVERAGE: '/progress/quizzes/average',
  QUIZ_COMPARE_COURSES: '/progress/quizzes/compare-courses',
  QUIZ_COMPARE_TIMEFRAMES: '/progress/quizzes/compare-timeframes',
  GENERATE_QUIZ: '/ai/generate/quiz',
  UPLOAD_FILE: '/files/upload',
} as const
