export const USER_API_ROUTES = {
  PROFILE: '/User/profile',
  UPDATE_PROFILE: '/User/profile',
  UPDATE_AVATAR: '/User/avatar',
  DELETE_AVATAR: '/User/avatar',
  PREFERENCES: '/User/preferences',
  UPDATE_PREFERENCES: '/User/preferences',
  RESET_PREFERENCES: '/User/preferences/reset',
  NOTIFICATION_SETTINGS: '/User/notification-settings',
  UPDATE_NOTIFICATION_SETTINGS: '/User/notification-settings',
  TEST_NOTIFICATION: '/User/notification-settings/test',
  ACTIVITY: '/User/activity',
  EXPORT_DATA: '/User/export',
  DELETE_ACCOUNT: '/User/account',
  DEACTIVATE_ACCOUNT: '/User/deactivate',
} as const
