export const PROGRESOS_API_ROUTES = {
  GLOBAL_STATS: '/performance/global',
  WEEKLY_TREND: '/performance/trends/weekly',
  MONTHLY_TREND: '/performance/trends/monthly',
  YEARLY_REPORT: '/performance/trends/yearly',
  RANKING: '/performance/ranking',
  GOALS: '/performance/goals',
  GOAL_PROGRESS: '/performance/goals/progress',
  GOAL_CHECK: '/performance/goals/check',
  ACHIEVEMENTS: '/performance/achievements',
  FLASHCARD_PROGRESS: '/progress/flashcards',
  FLASHCARD_PROGRESS_DECK: (deckId: number) => `/progress/flashcards/decks/${deckId}`,
  FLASHCARD_MASTERY: (deckId: number) => `/progress/flashcards/decks/${deckId}/mastery`,
  FLASHCARD_TREND: (deckId: number) => `/progress/flashcards/decks/${deckId}/mastery/trend`,
  FLASHCARD_WEEKLY: '/progress/flashcards/weekly',
  FLASHCARD_MONTHLY: '/progress/flashcards/monthly',
  QUIZ_PROGRESS: '/progress/quizzes',
  QUIZ_PROGRESS_BY_QUIZ: (quizId: number) => `/progress/quizzes/${quizId}`,
  QUIZ_PROGRESS_COURSE: (courseId: number) => `/progress/quizzes/courses/${courseId}`,
  QUIZ_AVERAGE: '/progress/quizzes/average',
  QUIZ_WEAK_TOPICS: (courseId: number) => `/progress/quizzes/courses/${courseId}/weak-topics`,
  QUIZ_IMPROVEMENT: '/progress/quizzes/improvement',
  QUIZ_COMPARE: '/progress/quizzes/compare',
  QUIZ_COMPARE_COURSES: '/progress/quizzes/compare-courses',
  QUIZ_COMPARE_TIMEFRAMES: '/progress/quizzes/compare-timeframes',
  COURSE_EXAM_PROGRESS: (courseId: number) => `/progress/exam/courses/${courseId}`,
  COURSE_READINESS: (courseId: number) => `/progress/exam/courses/${courseId}/readiness`,
  COURSE_WEAKNESSES: (courseId: number) => `/progress/exam/courses/${courseId}/weaknesses`,
  COURSE_PREDICTIONS: (courseId: number) => `/progress/exam/courses/${courseId}/predictions`,
  COURSE_RECOMMENDATIONS: (courseId: number) => `/progress/exam/courses/${courseId}/recommendations`,
} as const
