export const FLASHCARD_API_ROUTES = {
  UPLOAD_FILE: "/files/upload",
  GENERATE: "/ai/generate/flashcards",
  DECKS: "/decks",
  DECKS_MY: "/decks/my",
  DECK_BY_ID: (id: number) => `/decks/${id}`,
  DUPLICATE_DECK: (id: number) => `/decks/${id}/duplicate`,
  CREATE_DECK: "/decks",
  UPDATE_DECK: (id: number) => `/decks/${id}`,
  DELETE_DECK: (id: number) => `/decks/${id}`,
  CARDS: "/flashcards",
  ALL_CARDS: "/flashcards/all",
  CARDS_BY_DECK: (deckId: number) => `/decks/${deckId}/cards`,
  CARD_BY_ID: (id: number) => `/flashcards/${id}`,
  CREATE_CARD: (deckId: number) => `/decks/${deckId}/cards`,
  UPDATE_CARD: (id: number) => `/flashcards/${id}`,
  DELETE_CARD: (id: number) => `/flashcards/${id}`,
  REORDER_CARDS: (deckId: number) => `/decks/${deckId}/cards/reorder`,
  SEARCH_CARDS: "/flashcards/search",
  BULK_CREATE_CARDS: "/flashcards/bulk",
  BULK_UPDATE_CARDS: "/flashcards/bulk",
  BULK_DELETE_CARDS: "/flashcards/bulk-delete",
  IMPORT_CSV: "/flashcards/import/csv",
  IMPORT_JSON: "/flashcards/import/json",
  IMPORT_TEXT: "/flashcards/import-text",
  EXPORT_DECK: (deckId: number) => `/flashcards/export/${deckId}`,
  FLASHCARD_PROGRESS: (deckId: number) => `/progress/flashcards/decks/${deckId}`,
  FLASHCARD_PROGRESS_COURSE: (courseId: number) => `/progress/flashcards/courses/${courseId}`,
  FLASHCARD_PREDICTIONS: (deckId: number) => `/progress/flashcards/decks/${deckId}/predictions`,
  FLASHCARD_TIMELINE: (deckId: number) => `/progress/flashcards/decks/${deckId}/timeline`,
  DECK_MASTERY: (deckId: number) => `/progress/flashcards/decks/${deckId}/mastery`,
  STUDY_SESSION: '/study/sessions',
  STUDY_NEXT_CARD: (sessionId: number) => `/study/sessions/${sessionId}/next`,
  STUDY_SUBMIT_ANSWER: (sessionId: number) => `/study/sessions/${sessionId}/answer`,
  STUDY_END_SESSION: (sessionId: number) => `/study/sessions/${sessionId}/end`,
  STUDY_DUE_CARDS: (deckId: number) => `/study/decks/${deckId}/due`,
} as const;
