export const CRONOGRAMA_API_ROUTES = {
  BASE: '/schedules',
  SCHEDULES: '/schedules',
  SCHEDULE_BY_ID: (id: number) => `/schedules/${id}`,
  RANGE: '/schedules/range',
  CALENDAR_MONTH: '/schedules/calendar/month',
  CALENDAR_WEEK: '/schedules/calendar/week',
  CALENDAR_DAY: '/schedules/calendar/day',
  CALENDAR_AGENDA: '/schedules/calendar/agenda',
  RECURRING: '/schedules/recurring',
  RECURRING_BY_ID: (id: number) => `/schedules/recurring/${id}`,
  MARK_COMPLETE: (id: number) => `/schedules/${id}/complete`,
  MARK_INCOMPLETE: (id: number) => `/schedules/${id}/incomplete`,
  BULK_COMPLETE: '/schedules/bulk-complete',
  CONTENTS: (scheduleId: number) => `/schedules/${scheduleId}/contents`,
  CONTENT_BY_ID: (scheduleId: number, contentId: number) => `/schedules/${scheduleId}/contents/${contentId}`,
  AUTO_ASSIGN: (scheduleId: number) => `/schedules/${scheduleId}/contents/auto-assign`,
  PRIORITIZE_EXAM: (scheduleId: number) => `/schedules/${scheduleId}/contents/prioritize-exam`,
  PRIORITIZE_WEAKNESS: (scheduleId: number) => `/schedules/${scheduleId}/contents/prioritize-weakness`,
  SUGGEST_SESSION: (scheduleId: number) => `/schedules/${scheduleId}/contents/suggest-session`,
  SUGGEST_CONTENT: (scheduleId: number) => `/schedules/${scheduleId}/contents/suggest-content`,
  OPTIMIZE: '/schedules/contents/optimize',
} as const
